# Generated by Django 4.1 on 2024-01-10 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTopics',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_topics',
            },
        ),
    ]
