# Generated by Django 4.1 on 2024-01-10 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttopics',
            options={'verbose_name_plural': 'プロジェクトのトピック一覧'},
        ),
        migrations.RemoveField(
            model_name='projecttopics',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projecttopics',
            name='updated_at',
        ),
    ]
