# Generated by Django 4.1 on 2024-01-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_alter_projecttopics_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTopics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': '活動のトピック一覧',
                'db_table': 'activity_topics',
            },
        ),
        migrations.CreateModel(
            name='PortfolioTopics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'ポートフォリオのトピック一覧',
                'db_table': 'portfolio_topics',
            },
        ),
    ]
