# Generated by Django 4.1 on 2024-01-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_activitytopics_portfoliotopics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitytopics',
            old_name='topic_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='portfoliotopics',
            old_name='topic_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='projecttopics',
            old_name='topic_id',
            new_name='id',
        ),
    ]
