# Generated by Django 4.1 on 2024-01-15 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_rename_topic_id_activitytopics_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopcsCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'トピックスカテゴリ',
                'db_table': 'topics_category',
            },
        ),
        migrations.AddField(
            model_name='activitytopics',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_app.topcscategory'),
        ),
        migrations.AddField(
            model_name='projecttopics',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_app.topcscategory'),
        ),
    ]
