# Generated by Django 4.1 on 2024-01-30 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_rename_topcscategory_topicscategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MypageUserProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('account_id', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=7)),
                ('address', models.CharField(max_length=255)),
                ('member_type', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'マイページ_ユーザープロフィール',
                'db_table': 'mypage_user_profile',
            },
        ),
        migrations.AlterModelOptions(
            name='activitytopics',
            options={'verbose_name_plural': 'ダッシュボード_活動のトピック一覧'},
        ),
        migrations.AlterModelOptions(
            name='portfoliotopics',
            options={'verbose_name_plural': 'ダッシュボード_ポートフォリオのトピック一覧'},
        ),
        migrations.AlterModelOptions(
            name='projecttopics',
            options={'verbose_name_plural': 'ダッシュボード_プロジェクトのトピック一覧'},
        ),
        migrations.AlterField(
            model_name='projecttopics',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_app.topicscategory'),
        ),
    ]
