# Generated by Django 4.1 on 2024-01-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_mypageuserprofile_alter_activitytopics_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=100)),
                ('has_creatable_project', models.BooleanField(default=True)),
                ('cnt_project_limit', models.IntegerField(default=1)),
                ('cnt_project', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Util_料金プラン',
                'db_table': 'pricing_plan',
            },
        ),
        migrations.AlterModelOptions(
            name='topicscategory',
            options={'verbose_name_plural': 'Util_トピックスカテゴリ'},
        ),
    ]
