# Generated by Django 4.1 on 2024-01-30 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0010_pricingplan_alter_topicscategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypageuserprofile',
            name='member_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_app.pricingplan'),
        ),
    ]
