# Generated by Django 4.1 on 2024-01-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0012_mypageuserprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypageuserprofile',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
