# Generated by Django 5.0.1 on 2024-02-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0013_alter_mypageuserprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipsCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tips_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Util_Tipsカテゴリ',
                'db_table': 'tips_category',
            },
        ),
    ]
