# Generated by Django 5.0.1 on 2024-02-14 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0014_tipscategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipsContents',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=1000)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_app.tipscategory')),
            ],
            options={
                'verbose_name_plural': 'Tips_一覧',
                'db_table': 'tips',
            },
        ),
    ]
