# Generated by Django 5.0.1 on 2024-02-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0015_tipscontents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipscontents',
            name='content',
            field=models.TextField(),
        ),
    ]
