# Generated by Django 5.0.1 on 2024-02-16 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0016_alter_tipscontents_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipscategory',
            name='tips_path',
            field=models.CharField(default='tips', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tipscontents',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_app.tipscategory'),
        ),
    ]
