# Generated by Django 5.0.1 on 2024-02-17 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0017_tipscategory_tips_path_alter_tipscontents_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipscontents',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_app.tipscategory'),
        ),
    ]
