# Generated by Django 5.0.1 on 2024-03-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0019_mypageuserprofile_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypageuserprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='mypageuserprofile',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='mypageuserprofile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='mypageuserprofile',
            name='user_permissions',
        ),
    ]
