# Generated by Django 5.0.1 on 2024-03-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0021_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
